### ISSUE TITLE
Update Passenger documentation link

### ISSUE THREAD

**Issue by rbr** [ruby-amqp/rubybunny.info#32]
https://github.com/ruby-amqp/rubybunny.info/blob/772f29932a0c5faaf08ba6a3312bb322870c2c04/articles/connecting.md#using-bunny-with-passenger contains http://bit.ly/passenger-forking-gotchas link, which points to the deprecated Passenger docs.

The new docs are at https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods

**Comment by michaelklishin** [comment]
@rbr feel free to submit a PR that corrects the link.

**Comment by rbr** [comment]
I assumed the bit.ly-link was in between to easily change the underlying link.
Thank you for fixing it anyway.
