### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by ivan-kolmychek** [ruby-amqp/rubybunny.info#48]
If I understand correctly, right now rubybunny.info is not available via HTTPS, only via plain HTTP.
Are there any plans to add HTTPS?

**Comment by michaelklishin** [comment]
I already spend 100s of USD a year on domains for my open source projects. Spending at least as much on certificates is not something I'm looking forward to. In case something like Let's Encrypt would be an option, I'd consider it but currently there are not plans (or much demand) for the HTTPS version.

**Comment by shushugah** [comment]
For what it's worth, I've had success using Netlify as my host, and they automatically provision free HTTPS domains with my custom domains. See https://codecurious.org for example or https://techworkersberlin.com
